## Indexing and Slicing

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,4,4,5,6])
arr1[3]

4

In [3]:
arr1[-3]

4

In [4]:
arr1[-1]

6

In [5]:
arr1[0]

1

In [6]:
arr2 = np.array([[2,3,4],[4,5,6]])
arr2

array([[2, 3, 4],
       [4, 5, 6]])

In [7]:
arr2.ndim # to check dimension

2

In [8]:
arr2[1]

array([4, 5, 6])

In [9]:
arr2[1][1]

5

In [10]:
arr2[1,1]

5

In [11]:
arr2[0,2]

4

In [12]:
l1 = [[[2,3],[5,6],[3,4]],[[11,22],[22,33],[33,44]],[[111,222],[222,333],[444,555]]]
arr3 = np.array(l1)
arr3

array([[[  2,   3],
        [  5,   6],
        [  3,   4]],

       [[ 11,  22],
        [ 22,  33],
        [ 33,  44]],

       [[111, 222],
        [222, 333],
        [444, 555]]])

In [13]:
arr3.ndim

3

In [14]:
arr3[0]

array([[2, 3],
       [5, 6],
       [3, 4]])

In [15]:
arr3[1,1,0]

22

In [16]:
arr3[2,0,0]

111

## Slicing

In [17]:
arr1 = np.array([1,2,3,4,5,6,7])
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
arr1[:]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
arr1[-5:]

array([3, 4, 5, 6, 7])

In [20]:
arr1[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [21]:
arr1[1:-2]

array([2, 3, 4, 5])

In [22]:
arr2 = np.array([[2,3,4],[4,5,6]])
arr2

array([[2, 3, 4],
       [4, 5, 6]])

In [23]:
arr2[:,:] # all rows and all columns

array([[2, 3, 4],
       [4, 5, 6]])

In [24]:
arr2[:] # all rows and all columns

array([[2, 3, 4],
       [4, 5, 6]])

In [26]:
arr2[0,:] # first row and all columns

array([2, 3, 4])

In [27]:
arr2[:,1] # all rows and first index column

array([3, 5])

In [28]:
arr2[1,:2] # first index row and 0 and 1 index column

array([4, 5])

In [32]:
arr2[-2,-3:-1]

array([2, 3])

In [33]:
arr2[-2,-2::-1]

array([3, 2])

In [29]:
arr2[1,1:] # first index row and 1 and 2 index column

array([5, 6])

In [34]:
arr2 = np.array([[4,5,6],[7,8,9],[10,20,30],[11,22,33],[41,52,63],[741,852,963]])
arr2

array([[  4,   5,   6],
       [  7,   8,   9],
       [ 10,  20,  30],
       [ 11,  22,  33],
       [ 41,  52,  63],
       [741, 852, 963]])

In [37]:
arr2[:2,:2]

array([[4, 5],
       [7, 8]])

In [35]:
l1=[1,2,3,4,5]
l1[:2]

[1, 2]

In [40]:
arr2[1:3,1:]

array([[ 8,  9],
       [20, 30]])

In [44]:
arr2[3:,:2]

array([[ 11,  22],
       [ 41,  52],
       [741, 852]])

In [45]:
arr3 = np.array([[[4,5,6],[7,8,9],[10,20,30]],[[11,22,33],[41,52,63],[741,852,963]]])
arr3

array([[[  4,   5,   6],
        [  7,   8,   9],
        [ 10,  20,  30]],

       [[ 11,  22,  33],
        [ 41,  52,  63],
        [741, 852, 963]]])

In [47]:
arr3[1]

array([[ 11,  22,  33],
       [ 41,  52,  63],
       [741, 852, 963]])

In [50]:
arr3[0,1:,:2]

array([[ 7,  8],
       [10, 20]])

In [52]:
arr3[:,1:,:2]

array([[[  7,   8],
        [ 10,  20]],

       [[ 41,  52],
        [741, 852]]])

In [54]:
arr3[1,1,2]

63

In [55]:
arr3

array([[[  4,   5,   6],
        [  7,   8,   9],
        [ 10,  20,  30]],

       [[ 11,  22,  33],
        [ 41,  52,  63],
        [741, 852, 963]]])

In [56]:
arr3[:,1,-1]

array([ 9, 63])

In [59]:
arr3[:,1,2]

array([ 9, 63])

##  Convert to n-D array

In [60]:
arr1 = np.array([1,2,3,4,5])
arr1.ndim

1

In [63]:
arr2 = np.array([1,2,3,4,5], ndmin = 2)
print('Array is :',arr2)
print('Number of Dimensions are:',arr2.ndim)

Array is : [[1 2 3 4 5]]
Number of Dimensions are: 2


In [64]:
arr2 = np.array([1,2,3,4,5], ndmin = 3)
print('Array is :',arr2)
print('Number of Dimensions are:',arr2.ndim)

Array is : [[[1 2 3 4 5]]]
Number of Dimensions are: 3


In [65]:
arr2 = np.array([1,2,3,4,5], ndmin = 4)
print('Array is :',arr2)
print('Number of Dimensions are:',arr2.ndim)

Array is : [[[[1 2 3 4 5]]]]
Number of Dimensions are: 4


In [70]:
arr2 = np.array([[1,2],[3,4]] ,ndmin = 4)
print('Array is :\n',arr2)
print('Number of Dimensions are:',arr2.ndim)

Array is :
 [[[[1 2]
   [3 4]]]]
Number of Dimensions are: 4


In [69]:
arr2 = np.array([[1,2],[3,4]] ,ndmin = 2)
print('Array is :\n',arr2)
print('Number of Dimensions are:',arr2.ndim)

Array is :
 [[1 2]
 [3 4]]
Number of Dimensions are: 2


In [2]:
import numpy as np
arr2 = np.array([[1,2],[3,4]] ,ndmin = 1)
print('Array is :\n',arr2)
print('Number of Dimensions are:',arr2.ndim)

Array is :
 [[1 2]
 [3 4]]
Number of Dimensions are: 2


In [74]:
arr2 = np.array([1,2,3,4,5], ndmin = 4)
print('Array is :',arr2)
print('Number of Dimensions are:',arr2.ndim)
arr2 = np.array(arr2, ndmin = 1)
arr2.ndim

Array is : [[[[1 2 3 4 5]]]]
Number of Dimensions are: 4


4

## Reshape Function

In [75]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20,30])
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

Array is :
 [ 1  2  3  4  4  5  6  7  8 10 20 30]
Number of dimensions are : 1
Shape of an array is : (12,)


In [ ]:
1D shape >> (3,)
2D shape >> (3,4)
3D shape >> (3,4,5)

In [ ]:
12:
1,12
2,6
3,4
4,3
6,2
12,1

In [76]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20,30])

arr1 = arr1.reshape(1,12)
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

Array is :
 [[ 1  2  3  4  4  5  6  7  8 10 20 30]]
Number of dimensions are : 2
Shape of an array is : (1, 12)


In [77]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20,30])

arr1 = arr1.reshape(2,6)
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

Array is :
 [[ 1  2  3  4  4  5]
 [ 6  7  8 10 20 30]]
Number of dimensions are : 2
Shape of an array is : (2, 6)


In [78]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20,30])

arr1 = arr1.reshape(3,5)
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [79]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20,30])

arr1 = arr1.reshape(3,4)
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

Array is :
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8 10 20 30]]
Number of dimensions are : 2
Shape of an array is : (3, 4)


In [80]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20,30])

arr1 = arr1.reshape(4,3)
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

Array is :
 [[ 1  2  3]
 [ 4  4  5]
 [ 6  7  8]
 [10 20 30]]
Number of dimensions are : 2
Shape of an array is : (4, 3)


In [81]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20,30])

arr1 = arr1.reshape(6,2)
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

Array is :
 [[ 1  2]
 [ 3  4]
 [ 4  5]
 [ 6  7]
 [ 8 10]
 [20 30]]
Number of dimensions are : 2
Shape of an array is : (6, 2)


In [82]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20])

arr1 = arr1.reshape(6,2)
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

ValueError: cannot reshape array of size 11 into shape (6,2)

In [83]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20,30])

arr1 = arr1.reshape(12,1)
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

Array is :
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [10]
 [20]
 [30]]
Number of dimensions are : 2
Shape of an array is : (12, 1)


In [ ]:
1,1,12
1,2,6
2,2,3
1,3,4

In [84]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20,30])

arr1 = arr1.reshape(1,1,12)
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

Array is :
 [[[ 1  2  3  4  4  5  6  7  8 10 20 30]]]
Number of dimensions are : 3
Shape of an array is : (1, 1, 12)


In [85]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20,30])

arr1 = arr1.reshape(1,2,6)
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

Array is :
 [[[ 1  2  3  4  4  5]
  [ 6  7  8 10 20 30]]]
Number of dimensions are : 3
Shape of an array is : (1, 2, 6)


In [86]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20,30])

arr1 = arr1.reshape(2,2,3)
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

Array is :
 [[[ 1  2  3]
  [ 4  4  5]]

 [[ 6  7  8]
  [10 20 30]]]
Number of dimensions are : 3
Shape of an array is : (2, 2, 3)


In [87]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,10,20,30])

arr1 = arr1.reshape(3,2,2)
print('Array is :\n',arr1)
print('Number of dimensions are :', arr1.ndim)
print('Shape of an array is :',arr1.shape)

Array is :
 [[[ 1  2]
  [ 3  4]]

 [[ 4  5]
  [ 6  7]]

 [[ 8 10]
  [20 30]]]
Number of dimensions are : 3
Shape of an array is : (3, 2, 2)


In [88]:
arr2 = np.array([[2,3,4,5],[6,7,8,9],[10,20,30,40]])
print('Array is :\n',arr2)
print('Number of dimensions are :', arr2.ndim)
print('Shape of an array is :',arr2.shape)

Array is :
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 20 30 40]]
Number of dimensions are : 2
Shape of an array is : (3, 4)


In [89]:
arr2 = np.array([[2,3,4,5],[6,7,8,9],[10,20,30,40]])

arr2 = arr2.reshape(2,3,2)
print('Array is :\n',arr2)
print('Number of dimensions are :', arr2.ndim)
print('Shape of an array is :',arr2.shape)

Array is :
 [[[ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 20]
  [30 40]]]
Number of dimensions are : 3
Shape of an array is : (2, 3, 2)


In [90]:
arr2 = np.array([[2,3,4,5],[6,7,8,9],[10,20,30,40]])

arr2 = arr2.reshape(12)
print('Array is :\n',arr2)
print('Number of dimensions are :', arr2.ndim)
print('Shape of an array is :',arr2.shape)

Array is :
 [ 2  3  4  5  6  7  8  9 10 20 30 40]
Number of dimensions are : 1
Shape of an array is : (12,)


In [91]:
l1 = list(arr2)
print(l1,type(l1))

[2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40] <class 'list'>


In [92]:
l2 = arr2.tolist()
print(l2,type(l2))

[2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40] <class 'list'>


In [93]:
arr2 = np.array([[2,3,4,5],[6,7,8,9],[10,20,30,40]])
list2= arr2.tolist()
list2 # creates nested list

[[2, 3, 4, 5], [6, 7, 8, 9], [10, 20, 30, 40]]