In [1]:
import numpy as np

In [2]:
l1 = [3,4,5,6,7]

In [3]:
sum(l1)

25

In [4]:
l1 * 2

[3, 4, 5, 6, 7, 3, 4, 5, 6, 7]

In [5]:
arr = np.array(l1)
arr

array([3, 4, 5, 6, 7])

In [6]:
arr * 2

array([ 6,  8, 10, 12, 14])

In [7]:
arr /2

array([1.5, 2. , 2.5, 3. , 3.5])

In [8]:
arr **2

array([ 9, 16, 25, 36, 49], dtype=int32)

In [9]:
arr // 2

array([1, 2, 2, 3, 3], dtype=int32)

In [10]:
arr % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [11]:
arr = arr ** 3
result = arr.tolist()
result

[27, 64, 125, 216, 343]

In [12]:
l1 = [2,3,4]
l2 = [3,4,5]
l1 + l2

[2, 3, 4, 3, 4, 5]

In [13]:
a1 = np.array([2,3,4])
a2 = np.array([3,4,5])
a1 + a2

array([5, 7, 9])

In [14]:
a1 = np.array([2,3,4])
a2 = np.array([3,4,5])
a1*a2

array([ 6, 12, 20])

In [15]:
np.add(a1,a2)

array([5, 7, 9])

In [16]:
np.sum(a1)

9

In [17]:
a1 = np.array([[10,20],[30,40]])
a2 = np.array([[4,5],[2,5]])
print('Array1 is :\n',a1)
print('Array2 is :\n',a2)

Array1 is :
 [[10 20]
 [30 40]]
Array2 is :
 [[4 5]
 [2 5]]


### Matrix Addition

In [18]:
np.add(a1,a2)

array([[14, 25],
       [32, 45]])

In [19]:
np.multiply(a1,a2)

array([[ 40, 100],
       [ 60, 200]])

### Matrix Dot Product

In [20]:
matrix1 = np.array([[2,3],[4,6]])
matrix2 = np.array([[5,4],[2,5]])
print('matrix1 is :\n',matrix1)
print('matrix2 is :\n',matrix2)

matrix1 is :
 [[2 3]
 [4 6]]
matrix2 is :
 [[5 4]
 [2 5]]


In [21]:
np.dot(matrix1,matrix2)

# 2*5 + 3*2   2*4 + 3*5
# 4*5 + 6*2   4*4 +6*5

array([[16, 23],
       [32, 46]])

## Numpy Functions

#### 1. np.reshape

In [ ]:
we can change the shape of our array

#### 2. np.zeros

In [ ]:
np.zeros(shape,dtype ='int')
Returns an array of zero values
To create target Variable
Weights initialize in deep learning alogrithms
Default data type float

In [22]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [23]:
arr = np.zeros(5,dtype = 'int')
arr

array([0, 0, 0, 0, 0])

In [24]:
np.zeros(100,dtype = 'int')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
arr0 = np.zeros([5,2],dtype = 'int')
arr0

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [27]:
arr0 = np.zeros([4,5],dtype = 'int')
arr0

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
arr0 = np.zeros([3,3,2],dtype = 'int')
arr0

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [ ]:
# It creates array filled with zeros

### 3. np.ones()

In [29]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
arr1 = np.ones(10,dtype='int')
arr1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [31]:
arr1 = np.ones([2,3],dtype='int')
arr1

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
arr1 = np.ones([5,6],dtype='int')
arr1

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [33]:
arr1.shape

(5, 6)

In [34]:
import pandas as pd

In [35]:
df = pd.DataFrame(arr1)
df

0  1  2  3  4  5
0  1  1  1  1  1  1
1  1  1  1  1  1  1
2  1  1  1  1  1  1
3  1  1  1  1  1  1
4  1  1  1  1  1  1

### 4. np.arange()

In [36]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr1 = np.arange(10,20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
arr1 = np.arange(10,20,2)
arr1

array([10, 12, 14, 16, 18])

In [40]:
arr1 = np.arange(20,10,-1)
arr1

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [41]:
arr1 = np.arange(10,20,-1)
arr1

array([], dtype=int32)

In [43]:
arr1 = np.arange(10,30)
arr1.shape

(20,)

In [44]:
arr1.reshape(4,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
np.empty()