In [6]:
import numpy as np

### Around

In [1]:
round(4.12345)

4

In [2]:
round(4.12345,2)

4.12

In [5]:
round(4.12345,1)

4.1

In [7]:
np.around(2.63528)

3.0

In [8]:
np.around(2.63528,2)

2.64

In [9]:
np.around(2.8)

3.0

In [10]:
np.around(2.2)

2.0

In [11]:
array = np.around([[3.5,2.2],[5.6,4.9]])
array

array([[4., 2.],
       [6., 5.]])

### Copy()

In [12]:
arr1 = np.array([3,4,5,6,7])
arr1

array([3, 4, 5, 6, 7])

In [13]:
arr2 = arr1.copy() # deepcopy
arr2

array([3, 4, 5, 6, 7])

In [14]:
array1 = np.array([[3,2],[4,5]])
array2 = array1.copy()
print('Array1 is :\n',array1)
print('Array2 is :\n',array2)

Array1 is :
 [[3 2]
 [4 5]]
Array2 is :
 [[3 2]
 [4 5]]


In [16]:
array1[1,0]=100
array1

array([[  3,   2],
       [100,   5]])

In [17]:
array2

array([[3, 2],
       [4, 5]])

## np.where()

In [20]:
l1 = [2,3,4,5,4,6,4,7,8,9]
l1.index(4)

indices = [i for i,item in enumerate(l1) if item ==4]
indices

[2, 4, 6]

In [22]:
arr1 = np.array(l1)
arr1

#indices = np.where(condition)
indices = np.where(arr1 == 4)
indices

(array([2, 4, 6], dtype=int64),)

In [23]:
arr1 = np.array(l1)
arr1

indices = np.where(arr1 <= 4)
indices

(array([0, 1, 2, 4, 6], dtype=int64),)

In [24]:
arr1 = np.array(l1)
arr1

indices = np.where(arr1 != 4)
indices

(array([0, 1, 3, 5, 7, 8, 9], dtype=int64),)

In [26]:
arr1 = np.array(l1)
arr1

indices = np.where(arr1 > 4)
indices

(array([3, 5, 7, 8, 9], dtype=int64),)