## Numpy

In [ ]:
Numpy >> Numerical Python

In [ ]:
Application:
    1. Linear Algebra
    2. Statistics(mean,mode,median,std,var)
    3. Probability
    4. Image Processing
    5. Trigonometry (sin, cos, tan)etc.
    6. Random Number Generation
    7. Logarithmic

In [ ]:
It is collection of Homogenous data types
ndarray >> n dimentional array( 0D, 1D, 2D ,nd)
Numpy array is faster than list
Array can be created using list and tuple
Numpy is written in Python ,C and C++


In [5]:
import numpy as np

In [2]:
# np.array(list,tuple)

arr1 = np.array([1,2,3,4]) # List
print(type(arr1))
arr1

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [3]:
arr2 = np.array((2,2,3,5)) # TUple
arr2 ,type(arr2)

(array([2, 2, 3, 5]), numpy.ndarray)

In [7]:
l1 = [3,4,5,6,7]
array = np.array(l1)
array

array([3, 4, 5, 6, 7])

In [6]:
l = (1,1.5,'g')
l = np.array(l)
l

array(['1', '1.5', 'g'], dtype='<U32')

In [9]:
l1 = [3.0,4.1,5.2,6.3,7]
array = np.array(l1)
array

array([3. , 4.1, 5.2, 6.3, 7. ])

In [10]:
l1 = [3,4,5.2,6,7]
array = np.array(l1)
array

array([3. , 4. , 5.2, 6. , 7. ])

In [11]:
l1 = [3,4,5.2,6,7+5j]
array = np.array(l1)
array

array([3. +0.j, 4. +0.j, 5.2+0.j, 6. +0.j, 7. +5.j])

In [12]:
l1 = [3,4,5.2,6,'a']
array = np.array(l1)
array

array(['3', '4', '5.2', '6', 'a'], dtype='<U32')

In [4]:
l1 = [3,4,52,6,'a']
array = np.array(l1)
array

array(['3', '4', '52', '6', 'a'], dtype='<U11')

## Change the data types

In [14]:
array = np.array([3,4,5,6], dtype = 'int')
array

array([3, 4, 5, 6])

In [15]:
array = np.array([3,4,5,6], dtype = 'float')
array

array([3., 4., 5., 6.])

In [16]:
array = np.array([3,4,5,6], dtype = 'complex')
array

array([3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [17]:
array = np.array([3.0,4.1,5.3,6.5], dtype = 'int')
array

array([3, 4, 5, 6])

In [19]:
1.

1.0

In [21]:
array = np.array([3,4,5,6+7j], dtype = 'complex')
array

array([3.+0.j, 4.+0.j, 5.+0.j, 6.+7.j])

In [22]:
array = np.array([3,4,5,6+7j], dtype = 'float')
array

TypeError: can't convert complex to float

In [23]:
array = np.array([3,4,5,6+7j], dtype = 'int')
array

TypeError: can't convert complex to int

In [25]:
array = np.array([3,4,5.2,'s',1+2j])
array

array(['3', '4', '5.2', 's', '(1+2j)'], dtype='<U64')

In [27]:
array = np.array([3,4,5,6], dtype = 'str')
array

array(['3', '4', '5', '6'], dtype='<U1')

In [28]:
array = np.array([3,4,5,6], dtype = 'object')
array

array([3, 4, 5, 6], dtype=object)

In [29]:
array = np.array([3,4,5,6+4j], dtype = 'object')
array

array([3, 4, 5, (6+4j)], dtype=object)

In [ ]:
int >> float
float >> int
int >> complex
float >> complex 
int,float,complex >> str/object
complex !!>> int
complex !!>> float

## Dimensions in Array

### 1. 0-D

In [35]:
arr0 = np.array(13)
arr0.ndim
print('Number of Dimensions are : ', arr0.ndim)

Number of Dimensions are :  0


In [36]:
arr0 = np.array(1.3)
arr0.ndim
print('Number of Dimensions are : ', arr0.ndim)

Number of Dimensions are :  0


### 2. 1-D

In [37]:
arr1 = np.array([13,2,3,4,5])
arr1.ndim
print('Number of Dimensions are : ', arr1.ndim)

Number of Dimensions are :  1


In [38]:
arr1 = np.array([[13,2,3,4,5]])
arr1.ndim
print('Number of Dimensions are : ', arr1.ndim)

Number of Dimensions are :  2


In [39]:
arr1 = np.array([[[13,2,3,4,5]]])
arr1.ndim
print('Number of Dimensions are : ', arr1.ndim)

Number of Dimensions are :  3


In [41]:
arr1 = np.array([13])
arr1.ndim
print('Number of Dimensions are : ', arr1.ndim)

Number of Dimensions are :  1


In [46]:
arr1 = np.array([13,4])
print('Array is :',arr1)
print('Number of Dimensions are : ', arr1.ndim)
print('Shape of an array is :', arr1.shape)

Array is : [13  4]
Number of Dimensions are :  1
Shape of an array is : (2,)


### 3. 2-D

In [50]:
arr2 = np.array([[2,3],[4,5],[6,7]])
print('Array is :\n',arr2)
print('Number of Dimensions are : ', arr2.ndim)
print('Shape of an array is :', arr2.shape)

Array is :
 [[2 3]
 [4 5]
 [6 7]]
Number of Dimensions are :  2
Shape of an array is : (3, 2)


In [51]:
arr2 = np.array([[2,3],[4,5,6],[6,7]])
print('Array is :\n',arr2)
print('Number of Dimensions are : ', arr2.ndim)
print('Shape of an array is :', arr2.shape)

Array is :
 [list([2, 3]) list([4, 5, 6]) list([6, 7])]
Number of Dimensions are :  1
Shape of an array is : (3,)


<ipython-input-51-b25f86d04d86>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 = np.array([[2,3],[4,5,6],[6,7]])


In [52]:
arr2 = np.array([[2,3]])
print('Array is :\n',arr2)
print('Number of Dimensions are : ', arr2.ndim)
print('Shape of an array is :', arr2.shape)

Array is :
 [[2 3]]
Number of Dimensions are :  2
Shape of an array is : (1, 2)


In [53]:
arr2 = np.array([[2,3],[4,5]])
print('Array is :\n',arr2)
print('Number of Dimensions are : ', arr2.ndim)
print('Shape of an array is :', arr2.shape)

Array is :
 [[2 3]
 [4 5]]
Number of Dimensions are :  2
Shape of an array is : (2, 2)


In [54]:
arr2 = np.array([[2,3,4,5],[3,4,5,6]]) # Multiple 1D array
print('Array is :\n',arr2)
print('Number of Dimensions are : ', arr2.ndim)
print('Shape of an array is :', arr2.shape)

Array is :
 [[2 3 4 5]
 [3 4 5 6]]
Number of Dimensions are :  2
Shape of an array is : (2, 4)


In [55]:
arr2 = np.array([[2,3,4,5],[3,4,5,6],[4,5,6,7],[5,6,7,8]]) # Multiple 1D array
print('Array is :\n',arr2)
print('Number of Dimensions are : ', arr2.ndim)
print('Shape of an array is :', arr2.shape)

Array is :
 [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
Number of Dimensions are :  2
Shape of an array is : (4, 4)


In [56]:
arr2 = np.array([[2,3,4,5],[3,4,3,[5,6]],[4,5,6,7],[5,6,7,8]]) # Multiple 1D array
print('Array is :\n',arr2)
print('Number of Dimensions are : ', arr2.ndim)
print('Shape of an array is :', arr2.shape)

Array is :
 [[2 3 4 5]
 [3 4 3 list([5, 6])]
 [4 5 6 7]
 [5 6 7 8]]
Number of Dimensions are :  2
Shape of an array is : (4, 4)


<ipython-input-56-8c4e2449406e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 = np.array([[2,3,4,5],[3,4,3,[5,6]],[4,5,6,7],[5,6,7,8]]) # Multiple 1D array


### 4. 3-D

In [58]:
arr2 = np.array([[[2,3,4,5]]]) 
print('Array is :\n',arr2)
print('Number of Dimensions are : ', arr2.ndim)
print('Shape of an array is :', arr2.shape)

Array is :
 [[[2 3 4 5]]]
Number of Dimensions are :  3
Shape of an array is : (1, 1, 4)


In [61]:
arr2 = np.array([[[2,3],[4,5],[5,6]]]) 
print('Array is :\n',arr2)
print('Number of Dimensions are : ', arr2.ndim)
print('Shape of an array is :', arr2.shape)
# 1,3,2
# 1 >> number of 2D
# 3 >> number of 1D
# 2 >> number of 0D

Array is :
 [[[2 3]
  [4 5]
  [5 6]]]
Number of Dimensions are :  3
Shape of an array is : (1, 3, 2)


In [67]:
l1 = [[[2,3],[5,6],[3,4]],[[11,22],[22,33],[33,44]],[[111,222],[222,333],[444,555]]]

In [68]:
arr2 = np.array(l1) 
print('Array is :\n',arr2)
print('Number of Dimensions are : ', arr2.ndim)
print('Shape of an array is :', arr2.shape)


Array is :
 [[[  2   3]
  [  5   6]
  [  3   4]]

 [[ 11  22]
  [ 22  33]
  [ 33  44]]

 [[111 222]
  [222 333]
  [444 555]]]
Number of Dimensions are :  3
Shape of an array is : (3, 3, 2)


### 5. 4-D

In [69]:
arr2 = np.array([[[[2,3],[3,4],[5,6]]]]) 
print('Array is :\n',arr2)
print('Number of Dimensions are : ', arr2.ndim)
print('Shape of an array is :', arr2.shape)


Array is :
 [[[[2 3]
   [3 4]
   [5 6]]]]
Number of Dimensions are :  4
Shape of an array is : (1, 1, 3, 2)


In [ ]:
1D >> 0D
2D >> 1D >> 0D
3D >> 2D >> 1D >> 0D
4D >> 3D >> 2D >> 1D >> 0D

In [70]:
l1 = [3,4,5,6]
l1 + 2

TypeError: can only concatenate list (not "int") to list

In [72]:
arr1= np.array(l1)
arr1 + 2

array([5, 6, 7, 8])

In [73]:
l1 = [3,4,5,6]
l1/ 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [74]:
arr1= np.array(l1)
arr1/2

array([1.5, 2. , 2.5, 3. ])

In [75]:
arr1

array([3, 4, 5, 6])

In [76]:
np.array(l1)

array([3, 4, 5, 6])

In [77]:
list(arr1)

[3, 4, 5, 6]

In [ ]:
arr1 = np.array(20)
arr1