In [26]:
from sklearn.datasets import load_boston

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split,GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import mean_squared_error

In [3]:
boston = load_boston()
dir(boston)

['DESCR', 'data', 'feature_names', 'filename', 'target']

In [7]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [9]:
# boston.data
df = pd.DataFrame(boston.data,columns=boston.feature_names)
df['Target'] = boston.target
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  Target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  Target   506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [12]:
x = df.drop('Target', axis = 1)
y = df['Target']
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=10)
x_train

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
167   1.80028   0.0  19.58   0.0  0.605  5.877  79.2  2.4259   5.0  403.0   
318   0.40202   0.0   9.90   0.0  0.544  6.382  67.2  3.5325   4.0  304.0   
99    0.06860   0.0   2.89   0.0  0.445  7.416  62.5  3.4952   2.0  276.0   
307   0.04932  33.0   2.18   0.0  0.472  6.849  70.3  3.1827   7.0  222.0   
404  41.52920   0.0  18.10   0.0  0.693  5.531  85.4  1.6074  24.0  666.0   
..        ...   ...    ...   ...    ...    ...   ...     ...   ...    ...   
320   0.16760   0.0   7.38   0.0  0.493  6.426  52.3  4.5404   5.0  287.0   
15    0.62739   0.0   8.14   0.0  0.538  5.834  56.5  4.4986   4.0  307.0   
484   2.37857   0.0  18.10   0.0  0.583  5.871  41.9  3.7240  24.0  666.0   
125   0.16902   0.0  25.65   0.0  0.581  5.986  88.4  1.9929   2.0  188.0   
265   0.76162  20.0   3.97   0.0  0.647  5.560  62.8  1.9865   5.0  264.0   

     PTRATIO       B  LSTAT  
167     14.7  227.61  12.14  
318     18.4  395.21  10.36  
99      18.0  396.90   6.19  
307     18.4  396.90   7.53  
404     20.2  329.46  27.38  
..       ...     ...    ...  
320     19.6  396.90   7.20  
15      21.0  395.62   8.47  
484     20.2  370.73  13.34  
125     19.1  385.02  14.81  
265     13.0  392.40  10.45  

[379 rows x 13 columns]

## 1. Linear Regression

In [15]:
# Test Data  Accuracy
lr_model = LinearRegression()
lr_model.fit(x_train, y_train)
y_pred = lr_model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
accuracy = lr_model.score(x_test, y_test)
print('Testing Data MSE', mse)
print('Testing Data Accuracy',accuracy)

Testing Data MSE 32.44253669600661
Testing Data Accuracy 0.6745585065949415


In [17]:
# Train Data Acciracy
y_pred_train = lr_model.predict(x_train)
mse = mean_squared_error(y_train, y_pred_train)
accuracy = lr_model.score(x_train, y_train)
print('Training Data MSE', mse)
print('Training Data Accuracy',accuracy)

Training Data MSE 18.87900085091601
Training Data Accuracy 0.7575686094674801


## 2. Ridge Regression

In [34]:
# Test Data Accuracy
ridge_model = Ridge(alpha=0.19)
ridge_model.fit(x_train, y_train)
y_pred = ridge_model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
accuracy = ridge_model.score(x_test,y_test)
print('Testing Data MSE',mse)
print('Tesing Data Accuracy',accuracy)

Testing Data MSE 32.59237125711973
Tesing Data Accuracy 0.6730554680443726


In [35]:
# Train Data Accuracy
y_pred_train = ridge_model.predict(x_train)
mse = mean_squared_error(y_train, y_pred_train)
accuracy = ridge_model.score(x_train, y_train)
print('Training Data MSE', mse)
print('Training Data Accuracy',accuracy)

Training Data MSE 18.893364028713144
Training Data Accuracy 0.7573841672296031


## 3. Lasso Regression

In [36]:
# Test Data Accuracy
lasso_model = Lasso(alpha=0.01)
lasso_model.fit(x_train, y_train)
y_pred = lasso_model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
accuracy = lasso_model.score(x_test,y_test)
print('Testing Data MSE',mse)
print('Tesing Data Accuracy',accuracy)

Testing Data MSE 32.825215565496315
Tesing Data Accuracy 0.6707197320888587


In [37]:
# Train Data Accuracy
y_pred_train = lasso_model.predict(x_train)
mse = mean_squared_error(y_train, y_pred_train)
accuracy = lasso_model.score(x_train, y_train)
print('Training Data MSE', mse)
print('Training Data Accuracy',accuracy)

Training Data MSE 18.915255035582707
Training Data Accuracy 0.7571030576900964


## 4. Hyperameter Tuning

In [ ]:
To find best paramaters for Machine Learning Models
1. GridSearchCV
2. RandomizedSearchCV

In [29]:
a1 = np.arange(0.01, 1, 0.01)
a2 = np.arange(1,50)
alpha_array = np.append(a1, a2)
alpha_array

array([1.0e-02, 2.0e-02, 3.0e-02, 4.0e-02, 5.0e-02, 6.0e-02, 7.0e-02,
       8.0e-02, 9.0e-02, 1.0e-01, 1.1e-01, 1.2e-01, 1.3e-01, 1.4e-01,
       1.5e-01, 1.6e-01, 1.7e-01, 1.8e-01, 1.9e-01, 2.0e-01, 2.1e-01,
       2.2e-01, 2.3e-01, 2.4e-01, 2.5e-01, 2.6e-01, 2.7e-01, 2.8e-01,
       2.9e-01, 3.0e-01, 3.1e-01, 3.2e-01, 3.3e-01, 3.4e-01, 3.5e-01,
       3.6e-01, 3.7e-01, 3.8e-01, 3.9e-01, 4.0e-01, 4.1e-01, 4.2e-01,
       4.3e-01, 4.4e-01, 4.5e-01, 4.6e-01, 4.7e-01, 4.8e-01, 4.9e-01,
       5.0e-01, 5.1e-01, 5.2e-01, 5.3e-01, 5.4e-01, 5.5e-01, 5.6e-01,
       5.7e-01, 5.8e-01, 5.9e-01, 6.0e-01, 6.1e-01, 6.2e-01, 6.3e-01,
       6.4e-01, 6.5e-01, 6.6e-01, 6.7e-01, 6.8e-01, 6.9e-01, 7.0e-01,
       7.1e-01, 7.2e-01, 7.3e-01, 7.4e-01, 7.5e-01, 7.6e-01, 7.7e-01,
       7.8e-01, 7.9e-01, 8.0e-01, 8.1e-01, 8.2e-01, 8.3e-01, 8.4e-01,
       8.5e-01, 8.6e-01, 8.7e-01, 8.8e-01, 8.9e-01, 9.0e-01, 9.1e-01,
       9.2e-01, 9.3e-01, 9.4e-01, 9.5e-01, 9.6e-01, 9.7e-01, 9.8e-01,
       9.9e-01, 1.0e

## GridSearchCV

In [31]:
lasso_model = Lasso()
param_grid = {'alpha':alpha_array}
gscv_lasso_model = GridSearchCV(lasso_model, param_grid, cv=5)
gscv_lasso_model.fit(x_train,y_train)
gscv_lasso_model.best_estimator_

Lasso(alpha=0.01)

In [32]:
gscv_lasso_model.best_params_

{'alpha': 0.01}

In [33]:
ridge_model = Ridge()
param_grid = {'alpha':alpha_array}
gscv_ridge_model = GridSearchCV(ridge_model, param_grid, cv=5)
gscv_ridge_model.fit(x_train,y_train)
gscv_ridge_model.best_estimator_

Ridge(alpha=0.19)

## RandomizedSearchCV

In [40]:
lasso_model = Lasso()
param_grid = {'alpha':alpha_array}
rscv_lasso_model = RandomizedSearchCV(lasso_model, param_grid, cv=5)
rscv_lasso_model.fit(x_train,y_train)
rscv_lasso_model.best_estimator_

Lasso(alpha=0.02)

In [41]:
rscv_lasso_model.predict(x_test)

array([31.02265329, 31.75018399, 30.41708137, 22.97213004, 20.07103753,
       16.56073058, 35.92071646, 14.72410465, 23.91700234, 37.05709554,
       21.09733849, 29.93174169, 27.82333183, 33.69071575, 32.84456886,
       41.16089263, 24.79962469, 22.99117772, 25.48077529, 21.96482292,
       32.4837434 , 18.21306782, 25.1031715 , 25.29155757, 32.45151103,
       20.97259687, 19.47187157, 17.35352224, 37.60948945, -0.18130997,
       31.98948033, 31.95755257, 26.11008712, 24.12972784, 20.16713406,
       19.7627958 ,  4.0805614 , 34.78083369, 27.07110528, 27.47204219,
       34.63417576, 29.55253062, 18.41079871, 31.25593329, 17.7410877 ,
       28.36810372, 19.99182184, 21.44435454, 37.90075546, 16.62756286,
       24.28685502, 19.57819745, 24.26709598, 34.39670424, 27.01325674,
       35.1891613 , 20.76640636, 20.44784356, 18.62604656, 25.03506813,
       20.06843447, 23.30247971, 38.9412243 , 43.33404665, 30.41870616,
       16.95336497, 23.74529703,  3.29333566, 31.2204732 , 29.58

In [42]:
ridge_model = Ridge()
param_grid = {'alpha':alpha_array}
rscv_ridge_model = RandomizedSearchCV(ridge_model, param_grid, cv=5)
rscv_ridge_model.fit(x_train,y_train)
rscv_ridge_model.best_estimator_

Ridge(alpha=0.02)

In [43]:
rscv_ridge_model.predict(x_test)

array([31.11067885, 31.81829368, 30.55002906, 22.46118528, 18.85001987,
       16.28692508, 36.12514095, 14.62690703, 24.54860468, 37.27107255,
       21.28349774, 30.59855321, 27.94344042, 33.80166507, 33.24740112,
       40.78813827, 24.33589968, 23.28402588, 25.50597078, 21.13471773,
       32.78342416, 17.78808897, 25.35595177, 25.04726603, 32.51701888,
       20.49410011, 19.68575291, 16.95260757, 38.24405039,  0.66664   ,
       32.33474761, 32.19965833, 25.79405235, 23.96371396, 20.49771385,
       19.54545489,  3.88261267, 34.74873015, 26.92663245, 27.63067978,
       34.4811912 , 29.79405346, 18.35120847, 31.37462691, 18.13209317,
       28.2290325 , 19.28187086, 21.70324598, 38.24879351, 16.45256695,
       24.59342798, 19.48726085, 24.48555676, 34.4877449 , 26.68027906,
       34.8533348 , 20.91267864, 19.63620614, 18.52703769, 25.00365522,
       19.87012154, 23.46125022, 39.55300931, 42.97009275, 30.34680931,
       16.89493574, 23.88248146,  3.32773489, 31.43993576, 29.09

In [44]:
x_test

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
305  0.05479  33.0   2.18   0.0  0.472  6.616   58.1  3.3700   7.0  222.0   
193  0.02187  60.0   2.93   0.0  0.401  6.800    9.9  6.2196   1.0  265.0   
65   0.03584  80.0   3.37   0.0  0.398  6.290   17.8  6.6115   4.0  337.0   
349  0.02899  40.0   1.25   0.0  0.429  6.939   34.5  8.7921   1.0  335.0   
151  1.49632   0.0  19.58   0.0  0.871  5.404  100.0  1.5916   5.0  403.0   
..       ...   ...    ...   ...    ...    ...    ...     ...   ...    ...   
493  0.17331   0.0   9.69   0.0  0.585  5.707   54.0  2.3817   6.0  391.0   
142  3.32105   0.0  19.58   1.0  0.871  5.403  100.0  1.3216   5.0  403.0   
26   0.67191   0.0   8.14   0.0  0.538  5.813   90.3  4.6820   4.0  307.0   
173  0.09178   0.0   4.05   0.0  0.510  6.416   84.1  2.6463   5.0  296.0   
428  7.36711   0.0  18.10   0.0  0.679  6.193   78.1  1.9356  24.0  666.0   

     PTRATIO       B  LSTAT  
305     18.4  393.36   8.93  
193     15.6  393.37   5.03  
65      16.1  396.90   4.67  
349     19.7  389.85   5.89  
151     14.7  341.60  13.28  
..       ...     ...    ...  
493     19.2  396.90  12.01  
142     14.7  396.90  26.82  
26      21.0  376.88  14.81  
173     16.6  395.50   9.04  
428     20.2   96.73  21.52  

[127 rows x 13 columns]

In [47]:
rscv_ridge_model.predict([[1.23,20, 2.4,1.0, 0.512, 5.404, 60, 1.249, 4.0, 250, 15.6, 398,8]])

array([31.44497152])

In [48]:
y_pred = rscv_ridge_model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
accuracy = rscv_ridge_model.score(x_test,y_test)
print('Testing Data MSE',mse)
print('Tesing Data Accuracy',accuracy)

Testing Data MSE 32.45888252338608
Tesing Data Accuracy 0.6743945363566349


In [49]:
# Train Data Accuracy
y_pred_train = rscv_ridge_model.predict(x_train)
mse = mean_squared_error(y_train, y_pred_train)
accuracy = rscv_ridge_model.score(x_train, y_train)
print('Training Data MSE', mse)
print('Training Data Accuracy',accuracy)

Training Data MSE 18.87920909499404
Training Data Accuracy 0.7575659353375404
